### PR TITLE
Add a function to retrieve usable codes from named HTML entities

### PR DESCRIPTION
**Pull request by brandoncash**
This function returns the Unicode character for a given named HTML entity.  Instead of hunting up the code like `"\00b7"`, use `entity('middot')` to retrieve it.

Working example here: http://codepen.io/brandoncash/pen/LNRxQG

### CODE REVIEW

**Comment by besimhu** [comment]
I think this is neat, however, I don't believe it's something that should be included in the boilerplate. Some reasonings:
1. The moment we start adding helper functions to everything imaginable, that's the point it no longer becomes a boilerplate.
2. Besides emdash, ampersand, quotes, copy, & trademark ... I can't think off of any other readily used glyphs.
3. Going with point #2, now we have a rarely used chunk of code in our boilerplate that gets downloaded. Granted it won't get built unless called for, it's still a large piece of code that wouldn't get much traction. 

This is better served as a snippet. Even then, when I need a glyph, I just reference https://css-tricks.com/snippets/html/glyphs/ and I am supplied with much more data vs one Sass map.

**Comment by prichey** [comment]
This gets a 👍from me. Totally agree that we have to come up with a reasonable point somewhere between 'ultra minimal' and 'kitchen sink' (as far as what's included in the default boilerplate), but seeing as we have a bunch of stuff in there currently that really only is useful in a small handful of situations (keyframes, several things in utilities, extends), I don't have a problem throwing it in as well.

In any situation, I'm absolutely loving the use of CodePen to show a working example. 👍👍👍 for that.

**Comment by besimhu** [comment]
1. Keyframes are a fairly standard mixin that does get utilized if you're doing any sort of css animation.
2. There are some things in utilities not needed any longer with our switch to mostly IE9 sites. I agree with that.
3. extends has a few examples of how to write DRY CSS

Without actively knowing what you are looking for, it's just something else that would get little traction. 

I'd like a solid reason as to why this is handy to have in the boilerplate? This doesn't have a visual place I can easily reference to see what glyph to pull, and if I google, I am given the answer there. The Sass function is also utilizing the glyph abbreviations. Again, unless you know the abbreviation this just adds extra complexity.

Take for example `hellip`, do you off the top of your head know what that stands for?

**Comment by brandoncash** [comment]
I see the reluctance to need it, but it also pays off as quickly as `content: entity('middot');` for a bulleted list. They are the commonly used HTML entity names. `hellip` is a horizontal ellipsis; there are many you might not need but others that would be quite common.

**Comment by ghost** [comment]
gulp-eta will be deprecated, hence we will be closing the existing pull requests.

**Pull request closed without merging**
